### ISSUE TITLE
Message generation fails with multiple active tasks

### ISSUE THREAD

**Issue by jimmy-lt** [spack971/loggen#21]
Since we use a generator, when multiple active tasks are spawned message generation fails with the following:

```console
$ loggen -N 2 127.0.0.1 Test                                                               
Exception in thread loggen-a0:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/loggen/loggen/__init__.py", line 420, in task_active
    for msg in buffer:
ValueError: generator already executing
```

**Comment by jimmy-lt** [comment]
Fixed by #23.
